// Generated by scripts/build-ngrams.mjs — do not edit by hand.
// Public-domain passages (Project Gutenberg) from books NOT used for the n-gram statistics.
import type { BreakerLanguage } from '../types'

export interface Passage {
  source: string
  text: string
}

export const PASSAGES: Record<BreakerLanguage, Passage[]> = {
  "de": [
    {
      "source": "Kafka, Die Verwandlung",
      "text": "Er versuchte es daher, zuerst den Oberkoerper aus dem Bett zu bekommen, und drehte vorsichtig den Kopf dem Bettrand zu. Dies gelang auch leicht, und trotz ihrer Breite und Schwere folgte schliesslich die Koerpermasse langsam der Wendung des Kopfes. Aber als er den Kopf endlich ausserhalb des Bettes in der freien Luft hielt, bekam er Angst, weiter auf diese Weise vorzuruecken, denn wenn er sich schliesslich so fallen liess, musste geradezu ein Wunder geschehen wenn der Kopf nicht verletzt werden sollte. Und die Besinnung durfte er gerade jetzt um keinen Preis verlieren; lieber wollte er im Bett bleiben."
    },
    {
      "source": "Kafka, Die Verwandlung",
      "text": "Und waehrend Gregor dies alles hastig ausstiess und kaum wusste, was er sprach, hatte er sich leicht, wohl infolge der im Bett bereits erlangten Uebung, dem Kasten genaehert und versuchte nun, an ihm sich aufzurichten. Er wollte tatsaechlich die Tuer aufmachen, tatsaechlich sich sehen lassen und mit dem Prokuristen sprechen; er war begierig zu erfahren, was die anderen, die jetzt so nach ihm verlangten, bei seinem Anblick sagen wuerden. Wuerden sie erschrecken, dann hatte Gregor keine Verantwortung mehr und konnte ruhig sein. Wuerden sie aber alles ruhig hinnehmen, dann hatte auch er keinen Grund sich aufzuregen, und konnte, wenn er sich beeilte, um acht Uhr tatsaechlich auf dem Bahnhof sein."
    },
    {
      "source": "Kafka, Die Verwandlung",
      "text": "Erst in der Abenddaemmerung erwachte Gregor aus seinem schweren ohnmachtaehnlichen Schlaf. Er waere gewiss nicht viel spaeter auch ohne Stoerung erwacht, denn er fuehlte sich genuegend ausgeruht und ausgeschlafen, doch schien es ihm, als haette ihn ein fluechtiger Schritt und ein vorsichtiges Schliessen der zum Vorzimmer fuehrenden Tuer geweckt. Der Schein der elektrischen Strassenbahn lag bleich hier und da auf der Zimmerdecke und auf den hoeheren Teilen der Moebel, aber unten bei Gregor war es finster. Langsam schob er sich, noch ungeschickt mit seinen Fuehlern tastend, die er jetzt erst schaetzen lernte, zur Tuere hin, um nachzusehen, was dort geschehen war."
    },
    {
      "source": "Kafka, Die Verwandlung",
      "text": "Nun musste die Schwester im Verein mit der Mutter auch kochen; allerdings machte das nicht viel Muehe, denn man ass fast nichts. Immer wieder hoerte Gregor, wie der eine den anderen vergebens zum Essen aufforderte und keine andere Antwort bekam, als: »Danke ich habe genug« oder etwas Aehnliches. Getrunken wurde vielleicht auch nichts. Oefters fragte die Schwester den Vater, ob er Bier haben wolle, und herzlich erbot sie sich, es selbst zu holen, und als der Vater schwieg, sagte sie, um ihm jedes Bedenken zu nehmen, sie koenne auch die Hausmeisterin darum schicken, aber dann sagte der Vater schliesslich ein grosses »Nein«, und es wurde nicht mehr davon gesprochen."
    },
    {
      "source": "Kafka, Die Verwandlung",
      "text": "Beim Anhoeren dieser Worte der Mutter erkannte Gregor, dass der Mangel jeder unmittelbaren menschlichen Ansprache, verbunden mit dem einfoermigen Leben inmitten der Familie, im Laufe dieser zwei Monate seinen Verstand hatte verwirren muessen, denn anders konnte er es sich nicht erklaeren, dass er ernsthaft darnach hatte verlangen koennen, dass sein Zimmer ausgeleert wuerde. Hatte er wirklich Lust, das warme, mit ererbten Moebeln gemuetlich ausgestattete Zimmer in eine Hoehle verwandeln zu lassen, in der er dann freilich nach allen Richtungen ungestoert wuerde kriechen koennen, jedoch auch unter gleichzeitigem, schnellen, gaenzlichen Vergessen seiner menschlichen Vergangenheit?"
    },
    {
      "source": "Kafka, Die Verwandlung",
      "text": "Und wenn nun auch Gregor durch seine Wunde an Beweglichkeit wahrscheinlich fuer immer verloren hatte und vorlaeufig zur Durchquerung seines Zimmers wie ein alter Invalide lange, lange Minuten brauchte -- an das Kriechen in der Hoehe war nicht zu denken --, so bekam er fuer diese Verschlimmerung seines Zustandes einen seiner Meinung nach vollstaendig genuegenden Ersatz dadurch, dass immer gegen Abend die Wohnzimmertuer, die er schon ein bis zwei Stunden vorher scharf zu beobachten pflegte, geoeffnet wurde, so dass er, im Dunkel seines Zimmers liegend, vom Wohnzimmer aus unsichtbar, die ganze Familie beim beleuchteten Tische sehen und ihre Reden, gewissermassen mit allgemeiner Erlaubnis, also ganz anders als frueher, anhoeren durfte."
    },
    {
      "source": "Kafka, Die Verwandlung",
      "text": "Gerade an diesem Abend -- Gregor erinnerte sich nicht, waehrend der ganzen Zeit die Violine gehoert zu haben -- ertoente sie von der Kueche her. Die Zimmerherren hatten schon ihr Nachtmahl beendet, der mittlere hatte eine Zeitung hervorgezogen, den zwei anderen je ein Blatt gegeben, und nun lasen sie zurueckgelehnt und rauchten. Als die Violine zu spielen begann, wurden sie aufmerksam, erhoben sich und gingen auf den Fussspitzen zur Vorzimmertuer, in der sie aneinandergedraengt stehen blieben. Man musste sie von der Kueche aus gehoert haben, denn der Vater rief: »Ist den Herren das Spiel vielleicht unangenehm?"
    },
    {
      "source": "Kafka, Die Verwandlung",
      "text": "»Wenn er uns verstuende,« sagte der Vater halb fragend; die Schwester schuettelte aus dem Weinen heraus heftig die Hand zum Zeichen, dass daran nicht zu denken sei. »Wenn er uns verstuende,« wiederholte der Vater und nahm durch Schliessen der Augen die Ueberzeugung der Schwester von der Unmoeglichkeit dessen in sich auf, »dann waere vielleicht ein Uebereinkommen mit ihm moeglich. »Weg muss es,« rief die Schwester, »das ist das einzige Mittel, Vater. Du musst bloss den Gedanken loszuwerden suchen, dass es Gregor ist. Dass wir es so lange geglaubt haben, das ist ja unser eigentliches Unglueck."
    },
    {
      "source": "Hauff, Märchen-Almanach auf das Jahr 1828",
      "text": "„Habe bis jetzt noch nicht daran gedacht, gnaedige Frau Mutter“, erwiderte Kuno, „will mir deswegen andere Gesellschaft zur Unterhaltung ins Haus nehmen und bin deswegen mit der Saenfte hierhergereist. „Denn er kommt doch nicht mehr gut zu Pferde fort“, sprach Kuno ganz ruhig weiter, „der Pater Joseph naemlich, der Schlosskaplan. Ich will ihn zu mir nehmen, er ist mein alter Lehrer, und wir haben es so abgemacht, als ich Zollern verliess. Will auch unten am Berg die alte Frau Feldheimerin mitnehmen. Lieber Gott! Sie ist jetzt steinalt und hat mir einst das Leben gerettet, als ich zum erstenmal ausritt mit meinem seligen Vater; habe ja Zimmer genug in Hirschberg, und dort soll sie absterben."
    },
    {
      "source": "Hauff, Märchen-Almanach auf das Jahr 1828",
      "text": "„Das glaube ich nicht“, erwiderte der Student, „fuer so toericht kann ich diese Leute nicht halten, dass sie wegen des geringen Vorteils, den sie von uns haetten, vier Menschen ans Leben gehen sollten. Aber verteidigen duerfen wir uns nicht. Ich fuer meinen Teil werde wohl am meisten verlieren; mein Pferd ist schon in ihren Haenden, es kostete mich fuenfzig Dukaten noch vor vier Wochen; meine Boerse, meine Kleider gebe ich willig hin; denn mein Leben ist mir am Ende doch lieber als alles dies. „Ihr habt gut reden“, erwiderte der Fuhrmann, „solche Sachen, wie Ihr sie verlieren koennt, ersetzt Ihr Euch leicht wieder; aber ich bin der Bote von Aschaffenburg und habe allerlei Gueter auf meinem Karren, und im Stall zwei schoene Rosse, meinen einzigen Reichtum."
    },
    {
      "source": "Hauff, Märchen-Almanach auf das Jahr 1828",
      "text": "Mehrere Tage lang erinnerte ihn seine geschwollene Hand an seine Undankbarkeit und Torheit. Dann aber uebertaeubte er sein Gewissen und sprach: „Und wenn sie mir die Glashuette und alles verkaufen, so bleibt mir doch immer der dicke Ezechiel. So lange der Geld hat am Sonntag, kann es mir nicht fehlen. Ja, Peter! Aber wenn er keines hat?—Und so geschah es eines Tages und war ein wunderliches Rechenexempel. Denn eines Sonntags kam er angefahren ans Wirtshaus, und die Leute streckten die Koepfe durch die Fenster, und der eine sagte, da kommt der Spielpeter, und der andere, ja, der Tanzkaiser, der reiche Glasmann, und ein dritter schuettelte den Kopf und sprach: „Mit dem Reichtum kann man es machen, man sagt allerlei von seinen Schulden, und in der Stadt hat einer gesagt, der Amtmann werde nicht mehr lange saeumen zum Auspfaenden."
    },
    {
      "source": "Hauff, Märchen-Almanach auf das Jahr 1828",
      "text": "„So?“ sprach der Kaufmann, hoehnisch laechelnd. „An niemand anders wollt Ihr Euch wenden als an unseren allergnaedigsten Herrn? Das heisse ich vornehm betteln! Ei, ei! Bedenket aber, junger vornehmer Herr, dass der Weg zum Kalifen an meinem Vetter Messour vorbeigeht, und dass es mich ein Wort kostet, den Oberkaemmerer darauf aufmerksam zu machen, wie trefflich Ihr luegen koennet. Aber mich dauert deine Jugend, Said. Du kannst dich bessern, es kann noch etwas aus dir werden. Ich will dich in mein Gewoelbe im Basar nehmen, dort sollst du mir ein Jahr lang dienen, und ist dies vorbei und willst du nicht bei mir bleiben, so zahle ich dir deinen Lohn aus und lasse dich gehen, wohin du willst, nach Aleppo oder Medina, nach Stambul oder nach Balsora, meinetwegen zu den Unglaeubigen."
    },
    {
      "source": "Hauff, Märchen-Almanach auf das Jahr 1828",
      "text": "Pfeilschnell trug ihn sein wunderbares Pferd durch die Wogen, und noch ehe es Abend wurde, sah er Land und erkannte einen breiten Fluss, in welchen der Delphin auch sogleich einbog. Stromaufwaerts ging es langsamer, und um nicht verschmachten zu muessen, nahm Said, der sich aus alten Zaubergeschichten erinnerte, wie man zaubern muesse, das Pfeifchen heraus, pfiff laut und herzhaft und wuenschte sich dann ein gutes Mahl. Sogleich hielt der Fisch stille, und hervor aus dem Wasser tauchte ein Tisch, so wenig nass, als ob er acht Tage an der Sonne gestanden waere, und reich besetzt mit koestlichen Speisen."
    },
    {
      "source": "Hauff, Märchen-Almanach auf das Jahr 1828",
      "text": "Das Maennchen knirschte, schimpfte und fluchte ihm nach; aber der Fischer, welcher zu beiden Rudern gegriffen hatte, war ihm bald ausser Gehoer und, nachdem er um einen Felsen gebogen, auch aus dem Gesichte. Aber die Entdeckung, dass der boese Geist sich seinen Geiz zunutze zu machen und mit Gold in seine Schlingen zu locken suchte, heilte den verblendeten Fischer nicht, im Gegenteil, er meinte die Mitteilung des gelben Maennchens benuetzen zu koennen, ohne sich dem Boesen zu ueberliefern, und indem er fortfuhr, an der oeden Kueste nach Gold zu fischen, vernachlaessigte er den Wohlstand, den ihm die reichen Fischzuege in andern Gegenden des Meeres darboten, sowie alle andern Mittel, auf die er ehemals seinen Fleiss verwendet, und versank von Tag zu Tage nebst seinem Gefaehrten in tiefere Armut, bis es endlich oft an den notwendigsten Lebensbeduerfnissen zu fehlen anfing."
    },
    {
      "source": "Hauff, Märchen-Almanach auf das Jahr 1828",
      "text": "Die Graefin wagte vor Angst und Beben nicht zu antworten, sie fuerchtete, sich durch ihre zarte Stimme zu verraten. Der Zirkelschmied merkte es, nahm seinen Gefaehrten unter den Arm, sagte der Wirtin ade und stimmte ein lustiges Lied an, waehrend er dem Walde zuschnitt. „Jetzt erst bin ich in Sicherheit!“ rief die Graefin, als sie etwa hundert Schritte entfernt waren. „Noch immer glaubte ich, die Frau werde mich erkennen und durch ihre Knechte festnehmen. Oh, wie will ich euch allen danken! Kommet auch Ihr auf mein Schloss, Ihr muesst doch Euern Reisegenossen bei mir wieder abholen."
    },
    {
      "source": "Hauff, Märchen-Almanach auf das Jahr 1828",
      "text": "Er empfand keine Reue, dass er sie getoetet, aber wenn er dem Gesinde sagte, seine Frau sei verreist, so dachte er immer dabei: „Wohin mag sie wohl gereist sein?“ Sechs Tage hatte er es so getrieben, und immer hoerte er nachts diese Stimme, und immer dachte er an den Waldgeist und seine schreckliche Drohung; aber am siebenten Morgen sprang er auf von seinem Lager und rief: „Nun ja, will sehen, ob ich mir ein waermeres schaffen kann; denn der gleichgueltige Stein in meiner Brust macht mir das Leben nur langweilig und oede.“ Er zog schnell seinen Sonntagsstaat an und setzte sich auf sein Pferd und ritt dem Tannenbuehl zu."
    }
  ],
  "en": [
    {
      "source": "Doyle, The Hound of the Baskervilles",
      "text": "“It seems natural, does it not? And yet, consider that every Baskerville who goes there meets with an evil fate. I feel sure that if Sir Charles could have spoken with me before his death he would have warned me against bringing this, the last of the old race, and the heir to great wealth, to that deadly place. And yet it cannot be denied that the prosperity of the whole poor, bleak countryside depends upon his presence. All the good work which has been done by Sir Charles will crash to the ground if there is no tenant of the Hall. I fear lest I should be swayed too much by my own obvious interest in the matter, and that is why I bring the case before you and ask for your advice.”"
    },
    {
      "source": "Doyle, The Hound of the Baskervilles",
      "text": "As we came round the top of the stairs we had run up against Sir Henry Baskerville himself. His face was flushed with anger, and he held an old and dusty boot in one of his hands. So furious was he that he was hardly articulate, and when he did speak it was in a much broader and more Western dialect than any which we had heard from him in the morning. “Seems to me they are playing me for a sucker in this hotel,” he cried. “They’ll find they’ve started in to monkey with the wrong man unless they are careful. By thunder, if that chap can’t find my missing boot there will be trouble."
    },
    {
      "source": "Doyle, The Hound of the Baskervilles",
      "text": "The wheels died away down the drive while Sir Henry and I turned into the hall, and the door clanged heavily behind us. It was a fine apartment in which we found ourselves, large, lofty, and heavily raftered with huge baulks of age-blackened oak. In the great old-fashioned fireplace behind the high iron dogs a log-fire crackled and snapped. Sir Henry and I held out our hands to it, for we were numb from our long drive. Then we gazed round us at the high, thin window of old stained glass, the oak panelling, the stags’ heads, the coats of arms upon the walls, all dim and sombre in the subdued light of the central lamp."
    },
    {
      "source": "Doyle, The Hound of the Baskervilles",
      "text": "“No, no. I remember the thrill in your voice. I remember the look in your eyes. Please, please, be frank with me, Miss Stapleton, for ever since I have been here I have been conscious of shadows all round me. Life has become like that great Grimpen Mire, with little green patches everywhere into which one may sink and with no guide to point the track. Tell me then what it was that you meant, and I will promise to convey your warning to Sir Henry.” “You make too much of it, Dr. Watson,” said she. “My brother and I were very much shocked by the death of Sir Charles. We knew him very intimately, for his favourite walk was over the moor to our house."
    },
    {
      "source": "Doyle, The Hound of the Baskervilles",
      "text": "In five minutes we were outside the door, starting upon our expedition. We hurried through the dark shrubbery, amid the dull moaning of the autumn wind and the rustle of the falling leaves. The night air was heavy with the smell of damp and decay. Now and again the moon peeped out for an instant, but clouds were driving over the face of the sky, and just as we came out on the moor a thin rain began to fall. The light still burned steadily in front. As if in answer to his words there rose suddenly out of the vast gloom of the moor that strange cry which I had already heard upon the borders of the great Grimpen Mire."
    },
    {
      "source": "Doyle, The Hound of the Baskervilles",
      "text": "Luck had been against us again and again in this inquiry, but now at last it came to my aid. And the messenger of good fortune was none other than Mr. Frankland, who was standing, grey-whiskered and red-faced, outside the gate of his garden, which opened on to the highroad along which I travelled. “Good-day, Dr. Watson,” cried he with unwonted good humour, “you must really give your horses a rest and come in to have a glass of wine and to congratulate me.” My feelings towards him were very far from being friendly after what I had heard of his treatment of his daughter, but I was anxious to send Perkins and the wagonette home, and the opportunity was a good one."
    },
    {
      "source": "Doyle, The Hound of the Baskervilles",
      "text": "Then in an instant it was all clear to me. I remembered how the baronet had told me that he had handed his old wardrobe to Barrymore. Barrymore had passed it on in order to help Selden in his escape. Boots, shirt, cap—it was all Sir Henry’s. The tragedy was still black enough, but this man had at least deserved death by the laws of his country. I told Holmes how the matter stood, my heart bubbling over with thankfulness and joy. “Then the clothes have been the poor devil’s death,” said he. “It is clear enough that the hound has been laid on from some article of Sir Henry’s—the boot which was abstracted in the hotel, in all probability—and so ran this man down."
    },
    {
      "source": "Doyle, The Hound of the Baskervilles",
      "text": "“I think that on the whole you have had a fortunate escape,” said Sherlock Holmes. “You have had him in your power and he knew it, and yet you are alive. You have been walking for some months very near to the edge of a precipice. We must wish you good-morning now, Mrs. Lyons, and it is probable that you will very shortly hear from us again.” “Our case becomes rounded off, and difficulty after difficulty thins away in front of us,” said Holmes as we stood waiting for the arrival of the express from town. “I shall soon be in the position of being able to put into a single connected narrative one of the most singular and sensational crimes of modern times."
    },
    {
      "source": "Stevenson, Treasure Island",
      "text": "“Mother,” said I, “take the whole and let’s be going,” for I was sure the bolted door must have seemed suspicious and would bring the whole hornet’s nest about our ears, though how thankful I was that I had bolted it, none could tell who had never met that terrible blind man. But my mother, frightened as she was, would not consent to take a fraction more than was due to her and was obstinately unwilling to be content with less. It was not yet seven, she said, by a long way; she knew her rights and she would have them; and she was still arguing with me when a little low whistle sounded a good way off upon the hill."
    },
    {
      "source": "Stevenson, Treasure Island",
      "text": "“Well, sir,” said the captain, “better speak plain, I believe, even at the risk of offence. I don’t like this cruise; I don’t like the men; and I don’t like my officer. That’s short and sweet.” “Stay a bit,” said he, “stay a bit. No use of such questions as that but to produce ill feeling. The captain has said too much or he has said too little, and I’m bound to say that I require an explanation of his words. You don’t, you say, like this cruise. Now, why?” “I was engaged, sir, on what we call sealed orders, to sail this ship for that gentleman where he should bid me,” said the captain. “So far so good. But now I find that every man before the mast knows more than I do."
    },
    {
      "source": "Stevenson, Treasure Island",
      "text": "I thought this was a very bad sign, for up to that day the men had gone briskly and willingly about their business; but the very sight of the island had relaxed the cords of discipline. All the way in, Long John stood by the steersman and conned the ship. He knew the passage like the palm of his hand, and though the man in the chains got everywhere more water than was down in the chart, John never hesitated once. We brought up just where the anchor was in the chart, about a third of a mile from each shore, the mainland on one side and Skeleton Island on the other. The bottom was clean sand."
    },
    {
      "source": "Stevenson, Treasure Island",
      "text": "“I cannot keep her head for the stockade, sir,” said I to the captain. I was steering, while he and Redruth, two fresh men, were at the oars. “The tide keeps washing her down. Could you pull a little stronger?” I tried and found by experiment that the tide kept sweeping us westward until I had laid her head due east, or just about right angles to the way we ought to go. “If it’s the only course that we can lie, sir, we must even lie it,” returned the captain. “We must keep upstream. You see, sir,” he went on, “if once we dropped to leeward of the landing-place, it’s hard to say where we should get ashore, besides the chance of being boarded by the gigs; whereas, the way we go the current must slacken, and then we can dodge back along the shore.”"
    },
    {
      "source": "Stevenson, Treasure Island",
      "text": "“Doctor, you will take the door,” he resumed. “See, and don’t expose yourself; keep within, and fire through the porch. Hunter, take the east side, there. Joyce, you stand by the west, my man. Mr. Trelawney, you are the best shot--you and Gray will take this long north side, with the five loopholes; it’s there the danger is. If they can get up to it and fire in upon us through our own ports, things would begin to look dirty. Hawkins, neither you nor I are much account at the shooting; we’ll stand by to load and bear a hand.” As the captain had said, the chill was past. As soon as the sun had climbed above our girdle of trees, it fell with all its force upon the clearing and drank up the vapours at a draught."
    },
    {
      "source": "Stevenson, Treasure Island",
      "text": "The current was bearing coracle and schooner southward at an equal rate. As for the latter’s sailing, it was so wild and intermittent, and she hung each time so long in irons, that she certainly gained nothing, if she did not even lose. If only I dared to sit up and paddle, I made sure that I could overhaul her. The scheme had an air of adventure that inspired me, and the thought of the water breaker beside the fore companion doubled my growing courage. Up I got, was welcomed almost instantly by another cloud of spray, but this time stuck to my purpose and set myself, with all my strength and caution, to paddle after the unsteered HISPANIOLA."
    },
    {
      "source": "Stevenson, Treasure Island",
      "text": "The red glare of the torch, lighting up the interior of the block house, showed me the worst of my apprehensions realized. The pirates were in possession of the house and stores: there was the cask of cognac, there were the pork and bread, as before, and what tenfold increased my horror, not a sign of any prisoner. I could only judge that all had perished, and my heart smote me sorely that I had not been there to perish with them. There were six of the buccaneers, all told; not another man was left alive. Five of them were on their feet, flushed and swollen, suddenly called out of the first sleep of drunkenness."
    },
    {
      "source": "Stevenson, Treasure Island",
      "text": "The other men were variously burthened, some carrying picks and shovels--for that had been the very first necessary they brought ashore from the HISPANIOLA--others laden with pork, bread, and brandy for the midday meal. All the stores, I observed, came from our stock, and I could see the truth of Silver’s words the night before. Had he not struck a bargain with the doctor, he and his mutineers, deserted by the ship, must have been driven to subsist on clear water and the proceeds of their hunting. Water would have been little to their taste; a sailor is not usually a good shot; and besides all that, when they were so short of eatables, it was not likely they would be very flush of powder."
    }
  ]
}
