import type { BreakerLanguage } from './types'

/**
 * Quantised n-gram log10 probabilities (generated by scripts/build-ngrams.mjs):
 * log10 p = floor + q × step with q = table[index] in 0..255; index = letters in base 26.
 * Unseen n-grams sit at q = 0 (floor = log10(0.01 / total)).
 */
export interface NgramModel {
  language: BreakerLanguage
  bi: Uint8Array
  tri: Uint8Array
  quad: Uint8Array
  /** floor / step of the bigram, trigram and quadgram tables. */
  floor: [number, number, number]
  step: [number, number, number]
}

export const NGRAM_FILE_BYTES = 4 + 6 * 4 + 676 + 17576 + 456976

/** Parses an `ngrams-<lang>.bin` file. Throws on a malformed buffer. */
export function parseNgrams(data: ArrayBuffer | Uint8Array, language: BreakerLanguage): NgramModel {
  const bytes = data instanceof Uint8Array ? data : new Uint8Array(data)
  if (bytes.length !== NGRAM_FILE_BYTES) {
    throw new Error(`n-gram data for "${language}" has ${bytes.length} bytes, expected ${NGRAM_FILE_BYTES}`)
  }
  const magic = String.fromCharCode(bytes[0], bytes[1], bytes[2], bytes[3])
  if (magic !== 'NGR1') throw new Error(`n-gram data for "${language}" has an unknown format`)
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength)
  const floor: [number, number, number] = [0, 0, 0]
  const step: [number, number, number] = [0, 0, 0]
  for (let i = 0; i < 3; i++) {
    floor[i] = view.getFloat32(4 + i * 8, true)
    step[i] = view.getFloat32(8 + i * 8, true)
  }
  let offset = 28
  const take = (len: number): Uint8Array => {
    const t = bytes.slice(offset, offset + len)
    offset += len
    return t
  }
  return { language, bi: take(676), tri: take(17576), quad: take(456976), floor, step }
}

/** Sum of quantised n-gram values (order 2, 3 or 4) of letter codes. */
export function ngramSum(model: NgramModel, codes: ArrayLike<number>, order: 2 | 3 | 4): number {
  const n = codes.length
  let sum = 0
  if (order === 2) {
    const t = model.bi
    for (let i = 0; i + 1 < n; i++) sum += t[codes[i] * 26 + codes[i + 1]]
  } else if (order === 3) {
    const t = model.tri
    for (let i = 0; i + 2 < n; i++) sum += t[(codes[i] * 26 + codes[i + 1]) * 26 + codes[i + 2]]
  } else {
    const t = model.quad
    for (let i = 0; i + 3 < n; i++) {
      sum += t[((codes[i] * 26 + codes[i + 1]) * 26 + codes[i + 2]) * 26 + codes[i + 3]]
    }
  }
  return sum
}

/** Average log10 probability per n-gram (order 2–4); higher means more language-like. */
export function ngramLog10(model: NgramModel, codes: ArrayLike<number>, order: 2 | 3 | 4): number {
  const count = codes.length - order + 1
  if (count <= 0) return model.floor[order - 2]
  const k = order - 2
  return model.floor[k] + (model.step[k] * ngramSum(model, codes, order)) / count
}
